services:
  db:
    image: mysql:latest
    container_name: db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: users
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
  backend:
    build: ./back/
    container_name: back
    restart: always
    depends_on:
      - db
    environment:
      DATABASE_URL: "mysql://admin:admin@db:3306/users"
    ports:
      - "8000:8000"
    volumes:
      - ./back:/app
volumes:
  db_data: 