services:
  db:
    image: mysql:latest
    container_name: db_so
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: users
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./db:/docker-entrypoint-initdb.d #Importa el sql
  backend:
    build: ./back/
    container_name: back_so
    depends_on:
      - db
    ports:
      - "8000:8000"
    volumes:
      - ./back:/back

  frontend:
    build: ./front/
    container_name: front_so
    ports:
      - "3000:80"
    depends_on:
      - backend
    volumes:
      - ./front:/front
volumes:
  db_data: 